### PR TITLE
Schema version

### LINKED ISSUE #36: Adding schema version to responses from radelement.org API
cc: @talkasab - what version number would you like to assign to the current schema?

### PR DESCRIPTION
**Pull request by shadowdoc**
Renamed version -> [set_version, element_version] and added schema_version to both set and element levels.

Updated SampleDES.cde.json accordingly.

Closes #36

### CODE REVIEW

**Review by SuP3RM — APPROVED** [review]

**Comment by shadowdoc** [comment]
From @talkasab:

Would it be better to require the $schema element and have it point to a specific version of the schema rather than having to say, “Such and such version”, and then have to go look that up? The URL could effectively be the version.

My response:
Very interesting concept and probably a good idea. I think that $schema is required for JSON Schema compliance and we probably shouldn't overload or remove that. It looks like others suggest using $id. I found the third answer here particularly useful. https://stackoverflow.com/questions/61077293/is-there-a-standard-for-specifying-a-version-for-json-schema

**Comment by talkasab** [comment]
Could I propose that we use the `$id` field of the schema file itself to show a URL for the schema which is locked to a specific Github tag/release. The URL will include the tag/version information within it so it will be clear what version it is.
Then, each CDE Set JSON file can have the `$schema` property pointing to that fixed version of the schema.
Does this make sense?

**Comment by shadowdoc** [comment]
Following committee discussion we decided:
- schema_version will be required in all set documents
- element_version will be not be included in set documents
- element_version will be used ONLY in single element documents
- $id will be added to the schema and will be a URL pointing to a version in github

**Comment by shadowdoc** [comment]
@talkasab and @SuP3RM - can you review again? I believe we're ready.

**Pull request merged**
